# Generated by Django 4.0.5 on 2022-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
                ('p4', models.CharField(max_length=50)),
                ('p5', models.CharField(max_length=50)),
                ('p6', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maximeter_50_plus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('cups', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=100)),
                ('quarter_hour_curve', models.CharField(max_length=9999)),
                ('hired_power', models.CharField(max_length=100)),
                ('anual_consumption', models.CharField(blank=True, max_length=100)),
                ('optimal_anual_consumption', models.CharField(blank=True, max_length=100)),
                ('annual_savings', models.CharField(blank=True, max_length=100)),
                ('recomended_power', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maximeter_up_to_50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('cups', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=100)),
                ('quarter_hour_curve', models.CharField(max_length=9999)),
                ('hired_power', models.CharField(max_length=100)),
                ('anual_consumption', models.CharField(blank=True, max_length=100)),
                ('optimal_anual_consumption', models.CharField(blank=True, max_length=100)),
                ('annual_savings', models.CharField(blank=True, max_length=100)),
                ('recomended_power', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
