# Generated by Django 4.0.5 on 2022-07-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_constact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='constact_user',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
